### ISSUE TITLE
Base case parameter references. 

### ISSUE THREAD

**Issue by Maschette** [ccamlr/Grym_Base_Case#1]
Hi all looking at the parameters in the table below it would be good to identify where the values for parameters come from, the same as is done for icefish and toothfish. 
I also highlighted which ones need to be updated to area specific numbers for the base case scenarios, I haven't included size at maturity for area specific updates but talking to So this may be useful if there is data that can be used. 

If values are calculated for this assessment it would be good to have the code in another folder. If they are assumed, it would be good to get the rationale as a comment as it will contribute to the text of the assessment. 

Parameter | All areas | 48.1 | 48.2 | 48.3 | Reference | update needed?
-- | -- | -- | -- | -- | -- | --
First Age class | 0 |   |   |   | WG-EMM-2010 | maybe?
Last Age Class | 7 |   |   |   | WG-EMM-2010 | 
t0 | 0 |   |   |   |   |  
Linf | 60mm |   |   |   |   |  
k |   | 0.45 | 0.45 | 0.55 |   |  
Date - start growth period (dd/mm) |   | 21/10 | 21/10 | 09/10 |   |  
Date - end growth period (dd/mm) |   | 12/02 | 05/02 | 27/02 |   |  
Weight-length parameter – A (kg) | 1 |   |   |   | WG-EMM-2010 | Y
Weight-length parameter - B | 3 |   |   |   | WG-EMM-2010 | Y
Min length, 50% are mature | 31mm |   |   |   |   |  
Max length, 50% are mature | 36mm |   |   |   |   |  
Range over which maturity occurs | 12mm |   |   |   |   |  
First Day of Spawning Season (dd/mm) | 15/12 |   |   |   |   |  
Last Day of Spawning Season (dd/mm) | 15/02 |   |   |   |   |  
First Day of Survey (dd/mm) | 01/01 |   |   |   |   |  
Last Day of Survey (dd/mm) | 15/01 |   |   |   |   |  
Recruitment function | Beta |   |   |   |   |  
Mean recruitment | 0.5 |   |   |   | WG-EMM-2010 | Y
SD of recruitment | 0.25 |   |   |   | WG-EMM-2010 | Y
Min length, 50% Selected | 30mm |   |   |   |   |  
Max length, 50% Selected | 35mm |   |   |   |   |  
Range over which selection occurs | 11mm |   |   |   |   |  
Season | 1 Dec - 30 Nov |   |   |   | WG-EMM-2010 |  
Reference   Start Date in year | 1/10 |   |   |   |   |  
Reasonable upper bound for Annual F | 1.5 |   |   |   | WG-EMM-2010 |  
B0 log SD | 0.2 |   |   |   |   |  
Target Escapement | 75% |   |   |   |   |

**Comment by sthanassekos** [comment]
Lovely! I will write a document giving some of these references. Now busy working on mean and SD of recruitment per Subarea.

**Comment by Maschette** [comment]
Hi @sthanassekos , 
Are you able to update this with where we are at?

**Comment by sthanassekos** [comment]
@Maschette this is where we're at. Waiting for Spoon to get back to me regarding how to model VB growth when the reference date falls between the start and end of growth period. 


Parameter | All areas | 48.1 | 48.2 | 48.3 | Reference
-- | -- | -- | -- | -- | --
First Age class | 0 |   |   |   | Constable and de la Mare (1996)
Last Age Class | 7 |   |   |   | Constable and de la Mare (1996)
t0 | 0 |   |   |   | Constable and de la Mare (1996)
L∞ | 60mm |   |   |   | Constable and de la Mare (1996)
k |   | 0.48 | 0.45 | 0.55 | This study
Date - start growth   period (dd/mm) |   | 21/10 | 21/10 | 09/10 | This study
Date - end growth   period (dd/mm) |   | 12/02 | 05/02 | 27/02 | This study
Weight-length   parameter - A (mg) | 0.0043 |   |   |   | Siegel (2016)
Weight-length   parameter - B | 3.2446 |   |   |   | Siegel (2016)
Min length, 50% are   mature | 26mm |   |   |   | This study
Max length, 50% are   mature | 30mm |   |   |   | This study
Range over which   maturity occurs | 6mm |   |   |   | This study
First Day of   Spawning Season (dd/mm) | 15/12 |   |   |   | Kawaguchi (2016)
Last Day of   Spawning Season (dd/mm) | 15/02 |   |   |   | Kawaguchi (2016)
Monitoring interval   (dd/mm) | 01/01 to 14/01 |   |   |   | This study
Recruitment   function | Proportional |   |   |   | Constable and de la Mare (1996)
Mean proportional recruitment |   | 0.188/0.425* | 0.296 | 0.314 | CCAMLR Secretariat (2021)
SD of proportional recruitment |   | 0.236/0.170* | 0.260 | 0.278 | CCAMLR Secretariat (2021)
Min length, 50% Selected | 30mm |   |   |   | This study
Max length, 50%   Selected | 35mm |   |   |   | This study
Range over which   selection occurs | 11mm |   |   |   | This study
Fishing Season (dd/mm) | 01/12 to 30/11 |   |   |   | This study
Reference Start   Date in year (dd/mm) | 15/01 |   |   |   | This study
Reasonable upper   bound for Annual F | 1.5 |   |   |   | Constable and de la Mare (1996)
B0 log SD | 0.685 |   |   |   | This study
Target Escapement | 75% |   |   |   | Constable and de la Mare (1996)

*Values given for 481N/481S, see CCAMLR Secretariat (2021) for details.

**Comment by sthanassekos** [comment]
Closing this issue as the table of parameter values will be made available via e-group.
